/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './city.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
import * as import4 from 'ng2-bootstrap/modal/modal.module';
import * as import5 from '../shared/shared.module';
import * as import6 from '@angular/router';
import * as import7 from '../agenda/agenda.module';
import * as import8 from '../current-agenda/current-agenda.module';
import * as import9 from 'ng2-bootstrap/positioning/positioning.service';
import * as import10 from 'ng2-bootstrap/component-loader/component-loader.factory';
import * as import11 from '../agenda/agenda.service';
import * as import12 from './city.service';
import * as import13 from '../../node_modules/ng2-bootstrap/modal/modal-backdrop.component.ngfactory';
import * as import14 from '../agenda/agenda-list.component.ngfactory';
import * as import15 from '../agenda/agenda-details.component.ngfactory';
import * as import16 from './city-list.component.ngfactory';
import * as import17 from './city-details.component.ngfactory';
import * as import18 from '@angular/http';
import * as import19 from '../agenda/agenda-list.component';
import * as import20 from '../agenda/agenda-details.component';
import * as import21 from '../agenda/agenda.resolver';
import * as import22 from './city-list.component';
import * as import23 from './city-details.component';
import * as import24 from './city.resolver';
class CityModuleInjector extends import0.ɵNgModuleInjector<import1.CityModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _FormsModule_2:import3.FormsModule;
  _ModalModule_3:import4.ModalModule;
  _SharedModule_4:import5.SharedModule;
  _RouterModule_5:import6.RouterModule;
  _AgendaModule_6:import7.AgendaModule;
  _CurrentAgendaModule_7:import8.CurrentAgendaModule;
  _CityModule_8:import1.CityModule;
  __NgLocalization_9:import2.NgLocaleLocalization;
  __ɵi_10:import3.ɵi;
  __PositioningService_11:import9.PositioningService;
  __ComponentLoaderFactory_12:import10.ComponentLoaderFactory;
  _ROUTES_13:any[];
  __AgendaService_14:import11.AgendaService;
  __CityService_15:import12.CityService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import13.ModalBackdropComponentNgFactory,
      import14.AgendaListComponentNgFactory,
      import15.AgendaDetailsComponentNgFactory,
      import16.CityListComponentNgFactory,
      import17.CityDetailsComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_9():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_9 == null)) { (this.__NgLocalization_9 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_9;
  }
  get _ɵi_10():import3.ɵi {
    if ((this.__ɵi_10 == null)) { (this.__ɵi_10 = new import3.ɵi()); }
    return this.__ɵi_10;
  }
  get _PositioningService_11():import9.PositioningService {
    if ((this.__PositioningService_11 == null)) { (this.__PositioningService_11 = new import9.PositioningService()); }
    return this.__PositioningService_11;
  }
  get _ComponentLoaderFactory_12():import10.ComponentLoaderFactory {
    if ((this.__ComponentLoaderFactory_12 == null)) { (this.__ComponentLoaderFactory_12 = new import10.ComponentLoaderFactory(this.componentFactoryResolver,this.parent.get(import0.NgZone),this,this._PositioningService_11)); }
    return this.__ComponentLoaderFactory_12;
  }
  get _AgendaService_14():import11.AgendaService {
    if ((this.__AgendaService_14 == null)) { (this.__AgendaService_14 = new import11.AgendaService(this.parent.get(import18.Http))); }
    return this.__AgendaService_14;
  }
  get _CityService_15():import12.CityService {
    if ((this.__CityService_15 == null)) { (this.__CityService_15 = new import12.CityService(this.parent.get(import18.Http))); }
    return this.__CityService_15;
  }
  createInternal():import1.CityModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._FormsModule_2 = new import3.FormsModule();
    this._ModalModule_3 = new import4.ModalModule();
    this._SharedModule_4 = new import5.SharedModule();
    this._RouterModule_5 = new import6.RouterModule(this.parent.get(import6.ɵa,(null as any)),this.parent.get(import6.Router,(null as any)));
    this._AgendaModule_6 = new import7.AgendaModule();
    this._CurrentAgendaModule_7 = new import8.CurrentAgendaModule();
    this._CityModule_8 = new import1.CityModule();
    this._ROUTES_13 = [
      [
        {
          path: 'agenda',
          component: import19.AgendaListComponent
        }
        ,
        {
          path: 'agenda/:id',
          component: import20.AgendaDetailsComponent,
          resolve: {agenda: import21.AgendaResolver}
        }

      ]
      ,
      [
        {
          path: 'city',
          component: import22.CityListComponent
        }
        ,
        {
          path: 'city/:id',
          component: import23.CityDetailsComponent,
          resolve: {city: import24.CityResolver}
        }

      ]

    ]
    ;
    return this._CityModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.FormsModule)) { return this._FormsModule_2; }
    if ((token === import4.ModalModule)) { return this._ModalModule_3; }
    if ((token === import5.SharedModule)) { return this._SharedModule_4; }
    if ((token === import6.RouterModule)) { return this._RouterModule_5; }
    if ((token === import7.AgendaModule)) { return this._AgendaModule_6; }
    if ((token === import8.CurrentAgendaModule)) { return this._CurrentAgendaModule_7; }
    if ((token === import1.CityModule)) { return this._CityModule_8; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_9; }
    if ((token === import3.ɵi)) { return this._ɵi_10; }
    if ((token === import9.PositioningService)) { return this._PositioningService_11; }
    if ((token === import10.ComponentLoaderFactory)) { return this._ComponentLoaderFactory_12; }
    if ((token === import6.ROUTES)) { return this._ROUTES_13; }
    if ((token === import11.AgendaService)) { return this._AgendaService_14; }
    if ((token === import12.CityService)) { return this._CityService_15; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const CityModuleNgFactory:import0.NgModuleFactory<import1.CityModule> = new import0.NgModuleFactory<any>(CityModuleInjector,import1.CityModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvc3VlX2MwMC9jb2RlL2phcGFubmluZy9qYXBhbm5pbmcvc3JjL2FwcC9jaXR5L2NpdHkubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2pvc3VlX2MwMC9jb2RlL2phcGFubmluZy9qYXBhbm5pbmcvc3JjL2FwcC9jaXR5L2NpdHkubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
