/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './shared.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
import * as import4 from 'ng2-bootstrap/modal/modal.module';
import * as import5 from 'ng2-bootstrap/positioning/positioning.service';
import * as import6 from 'ng2-bootstrap/component-loader/component-loader.factory';
import * as import7 from '../../node_modules/ng2-bootstrap/modal/modal-backdrop.component.ngfactory';
class SharedModuleInjector extends import0.ɵNgModuleInjector<import1.SharedModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _FormsModule_2:import3.FormsModule;
  _ModalModule_3:import4.ModalModule;
  _SharedModule_4:import1.SharedModule;
  __NgLocalization_5:import2.NgLocaleLocalization;
  __ɵi_6:import3.ɵi;
  __PositioningService_7:import5.PositioningService;
  __ComponentLoaderFactory_8:import6.ComponentLoaderFactory;
  constructor(parent:import0.Injector) {
    super(parent,[import7.ModalBackdropComponentNgFactory],([] as any[]));
  }
  get _NgLocalization_5():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_5 == null)) { (this.__NgLocalization_5 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_5;
  }
  get _ɵi_6():import3.ɵi {
    if ((this.__ɵi_6 == null)) { (this.__ɵi_6 = new import3.ɵi()); }
    return this.__ɵi_6;
  }
  get _PositioningService_7():import5.PositioningService {
    if ((this.__PositioningService_7 == null)) { (this.__PositioningService_7 = new import5.PositioningService()); }
    return this.__PositioningService_7;
  }
  get _ComponentLoaderFactory_8():import6.ComponentLoaderFactory {
    if ((this.__ComponentLoaderFactory_8 == null)) { (this.__ComponentLoaderFactory_8 = new import6.ComponentLoaderFactory(this.componentFactoryResolver,this.parent.get(import0.NgZone),this,this._PositioningService_7)); }
    return this.__ComponentLoaderFactory_8;
  }
  createInternal():import1.SharedModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._FormsModule_2 = new import3.FormsModule();
    this._ModalModule_3 = new import4.ModalModule();
    this._SharedModule_4 = new import1.SharedModule();
    return this._SharedModule_4;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.FormsModule)) { return this._FormsModule_2; }
    if ((token === import4.ModalModule)) { return this._ModalModule_3; }
    if ((token === import1.SharedModule)) { return this._SharedModule_4; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_5; }
    if ((token === import3.ɵi)) { return this._ɵi_6; }
    if ((token === import5.PositioningService)) { return this._PositioningService_7; }
    if ((token === import6.ComponentLoaderFactory)) { return this._ComponentLoaderFactory_8; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SharedModuleNgFactory:import0.NgModuleFactory<import1.SharedModule> = new import0.NgModuleFactory<any>(SharedModuleInjector,import1.SharedModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvc3VlX2MwMC9jb2RlL2phcGFubmluZy9qYXBhbm5pbmcvc3JjL2FwcC9zaGFyZWQvc2hhcmVkLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9qb3N1ZV9jMDAvY29kZS9qYXBhbm5pbmcvamFwYW5uaW5nL3NyYy9hcHAvc2hhcmVkL3NoYXJlZC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
