/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './current-agenda.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
import * as import4 from 'ng2-bootstrap/modal/modal.module';
import * as import5 from '../shared/shared.module';
import * as import6 from '@angular/router';
import * as import7 from '../agenda/agenda.module';
import * as import8 from 'ng2-bootstrap/positioning/positioning.service';
import * as import9 from 'ng2-bootstrap/component-loader/component-loader.factory';
import * as import10 from '../agenda/agenda.service';
import * as import11 from '../../node_modules/ng2-bootstrap/modal/modal-backdrop.component.ngfactory';
import * as import12 from '../agenda/agenda-list.component.ngfactory';
import * as import13 from '../agenda/agenda-details.component.ngfactory';
import * as import14 from '@angular/http';
import * as import15 from '../agenda/agenda-list.component';
import * as import16 from '../agenda/agenda-details.component';
import * as import17 from '../agenda/agenda.resolver';
class CurrentAgendaModuleInjector extends import0.ɵNgModuleInjector<import1.CurrentAgendaModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _FormsModule_2:import3.FormsModule;
  _ModalModule_3:import4.ModalModule;
  _SharedModule_4:import5.SharedModule;
  _RouterModule_5:import6.RouterModule;
  _AgendaModule_6:import7.AgendaModule;
  _CurrentAgendaModule_7:import1.CurrentAgendaModule;
  __NgLocalization_8:import2.NgLocaleLocalization;
  __ɵi_9:import3.ɵi;
  __PositioningService_10:import8.PositioningService;
  __ComponentLoaderFactory_11:import9.ComponentLoaderFactory;
  _ROUTES_12:any[];
  __AgendaService_13:import10.AgendaService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import11.ModalBackdropComponentNgFactory,
      import12.AgendaListComponentNgFactory,
      import13.AgendaDetailsComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_8():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_8 == null)) { (this.__NgLocalization_8 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_8;
  }
  get _ɵi_9():import3.ɵi {
    if ((this.__ɵi_9 == null)) { (this.__ɵi_9 = new import3.ɵi()); }
    return this.__ɵi_9;
  }
  get _PositioningService_10():import8.PositioningService {
    if ((this.__PositioningService_10 == null)) { (this.__PositioningService_10 = new import8.PositioningService()); }
    return this.__PositioningService_10;
  }
  get _ComponentLoaderFactory_11():import9.ComponentLoaderFactory {
    if ((this.__ComponentLoaderFactory_11 == null)) { (this.__ComponentLoaderFactory_11 = new import9.ComponentLoaderFactory(this.componentFactoryResolver,this.parent.get(import0.NgZone),this,this._PositioningService_10)); }
    return this.__ComponentLoaderFactory_11;
  }
  get _AgendaService_13():import10.AgendaService {
    if ((this.__AgendaService_13 == null)) { (this.__AgendaService_13 = new import10.AgendaService(this.parent.get(import14.Http))); }
    return this.__AgendaService_13;
  }
  createInternal():import1.CurrentAgendaModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._FormsModule_2 = new import3.FormsModule();
    this._ModalModule_3 = new import4.ModalModule();
    this._SharedModule_4 = new import5.SharedModule();
    this._RouterModule_5 = new import6.RouterModule(this.parent.get(import6.ɵa,(null as any)),this.parent.get(import6.Router,(null as any)));
    this._AgendaModule_6 = new import7.AgendaModule();
    this._CurrentAgendaModule_7 = new import1.CurrentAgendaModule();
      this._ROUTES_12 = [[
        {
          path: 'agenda',
          component: import15.AgendaListComponent
        }
        ,
        {
          path: 'agenda/:id',
          component: import16.AgendaDetailsComponent,
          resolve: {agenda: import17.AgendaResolver}
        }

      ]
    ];
    return this._CurrentAgendaModule_7;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.FormsModule)) { return this._FormsModule_2; }
    if ((token === import4.ModalModule)) { return this._ModalModule_3; }
    if ((token === import5.SharedModule)) { return this._SharedModule_4; }
    if ((token === import6.RouterModule)) { return this._RouterModule_5; }
    if ((token === import7.AgendaModule)) { return this._AgendaModule_6; }
    if ((token === import1.CurrentAgendaModule)) { return this._CurrentAgendaModule_7; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_8; }
    if ((token === import3.ɵi)) { return this._ɵi_9; }
    if ((token === import8.PositioningService)) { return this._PositioningService_10; }
    if ((token === import9.ComponentLoaderFactory)) { return this._ComponentLoaderFactory_11; }
    if ((token === import6.ROUTES)) { return this._ROUTES_12; }
    if ((token === import10.AgendaService)) { return this._AgendaService_13; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const CurrentAgendaModuleNgFactory:import0.NgModuleFactory<import1.CurrentAgendaModule> = new import0.NgModuleFactory<any>(CurrentAgendaModuleInjector,import1.CurrentAgendaModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvc3VlX2MwMC9jb2RlL2phcGFubmluZy9qYXBhbm5pbmcvc3JjL2FwcC9jdXJyZW50LWFnZW5kYS9jdXJyZW50LWFnZW5kYS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvam9zdWVfYzAwL2NvZGUvamFwYW5uaW5nL2phcGFubmluZy9zcmMvYXBwL2N1cnJlbnQtYWdlbmRhL2N1cnJlbnQtYWdlbmRhLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
