/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.current[_ngcontent-%COMP%] {\n	position: absolute;\n    margin-top: -34.3em; \n	width: 24%;\n	margin-left: .42em;\n	border-radius: 4px;\n	border: 2pt solid salmon;\n	display: flex;\n	flex-flow: column;\n}\n\n#dropdownMenuButton[_ngcontent-%COMP%] {\n	margin-top: 1em;\n	margin-bottom: 1em;\n	margin-left: 5.3em;\n}\n\n.custom-bullett[_ngcontent-%COMP%]   li[_ngcontent-%COMP%] {\n    display: block;\n    margin-left: 7.5em;\n}\n\ni.fa.fa-heart[_ngcontent-%COMP%] {\n	padding-right: 2pt;\n	margin-left: -6em;\n	color: #5bc0de;\n}\n\n.deletePlan[_ngcontent-%COMP%] {\n	margin-left: 11.4em;\n	position: absolute;\n	margin-top: -1.6em;\n	padding-top: 1px;\n	padding-bottom: 1px;\n	padding-right: 2px;\n	padding-left: 2px;\n}\n\n.inputBox[_ngcontent-%COMP%] {\n	width: 50%;\n	margin-left: 5em;\n	text-align: center;\n	border-radius: .2em;\n}\n\n.addDay[_ngcontent-%COMP%] {\n	margin-bottom: 1em;\n	margin-left: 7.8em;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvc3VlX2MwMC9jb2RlL2phcGFubmluZy9qYXBhbm5pbmcvc3JjL2FwcC9jdXJyZW50LWFnZW5kYS9jdXJyZW50LWFnZW5kYS5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2pvc3VlX2MwMC9jb2RlL2phcGFubmluZy9qYXBhbm5pbmcvc3JjL2FwcC9jdXJyZW50LWFnZW5kYS9jdXJyZW50LWFnZW5kYS5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
