/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['a.navbar-brand[_ngcontent-%COMP%] {\n	padding-top: 12px;\n	color: #eee;  \n}\n\na.navbar-brand[_ngcontent-%COMP%]:hover {\n	color: #ef6c33;\n}\n\n.navbar-nav[_ngcontent-%COMP%] > li[_ngcontent-%COMP%] > a[_ngcontent-%COMP%] {\n	color: #eee;\n}\n\n.navbar-nav[_ngcontent-%COMP%] > li[_ngcontent-%COMP%] > a[_ngcontent-%COMP%]:hover {\n	color: #10c1c1;\n	text-decoration: none;\n}\n\n.navbar[_ngcontent-%COMP%] {\n	background-color: #69163F;\n}\n\n.navbar-nav[_ngcontent-%COMP%] {\n	margin-left: 41.5em;\n	margin-top: 1.5px;\n}\n\ndiv.container[_ngcontent-%COMP%] {\n	display: inline-flex;\n}\n\n#bs-example-navbar-collapse-1[_ngcontent-%COMP%] {\n    display: -webkit-box;\n    float: right;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvc3VlX2MwMC9jb2RlL2phcGFubmluZy9qYXBhbm5pbmcvc3JjL2FwcC9hcHAuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9qb3N1ZV9jMDAvY29kZS9qYXBhbm5pbmcvamFwYW5uaW5nL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
