/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './app.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/router';
import * as import4 from '@angular/platform-browser';
import * as import5 from '@angular/http';
import * as import6 from '@angular/forms';
import * as import7 from 'ng2-bootstrap/modal/modal.module';
import * as import8 from 'angular2-fontawesome/src/index';
import * as import9 from './shared/shared.module';
import * as import10 from './agenda/agenda.module';
import * as import11 from './current-agenda/current-agenda.module';
import * as import12 from './city/city.module';
import * as import13 from 'ng2-bootstrap/positioning/positioning.service';
import * as import14 from 'ng2-bootstrap/component-loader/component-loader.factory';
import * as import15 from './agenda/agenda.service';
import * as import16 from './city/city.service';
import * as import17 from './agenda/agenda.resolver';
import * as import18 from './city/city.resolver';
import * as import19 from '../node_modules/ng2-bootstrap/modal/modal-backdrop.component.ngfactory';
import * as import20 from './agenda/agenda-list.component.ngfactory';
import * as import21 from './agenda/agenda-details.component.ngfactory';
import * as import22 from './city/city-list.component.ngfactory';
import * as import23 from './city/city-details.component.ngfactory';
import * as import24 from './app.component.ngfactory';
import * as import25 from './agenda/agenda-list.component';
import * as import26 from './agenda/agenda-details.component';
import * as import27 from './city/city-list.component';
import * as import28 from './city/city-details.component';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ErrorHandler_1:any;
  _NgProbeToken_2:any[];
  _ɵg_3:import3.ɵg;
  _APP_INITIALIZER_4:any[];
  _ApplicationInitStatus_5:import0.ApplicationInitStatus;
  _ɵf_6:import0.ɵf;
  _ApplicationRef_7:any;
  _ApplicationModule_8:import0.ApplicationModule;
  _BrowserModule_9:import4.BrowserModule;
  _HttpModule_10:import5.HttpModule;
  _ɵba_11:import6.ɵba;
  _FormsModule_12:import6.FormsModule;
  _ModalModule_13:import7.ModalModule;
  _Angular2FontawesomeModule_14:import8.Angular2FontawesomeModule;
  _ɵa_15:any;
  _UrlSerializer_16:import3.DefaultUrlSerializer;
  _RouterOutletMap_17:import3.RouterOutletMap;
  _ROUTER_CONFIGURATION_18:any;
  _LocationStrategy_19:any;
  _Location_20:import2.Location;
  _Compiler_21:import0.Compiler;
  _NgModuleFactoryLoader_22:import0.SystemJsNgModuleLoader;
  _ROUTES_23:any[];
  _Router_24:any;
  _RouterModule_25:import3.RouterModule;
  _SharedModule_26:import9.SharedModule;
  _AgendaModule_27:import10.AgendaModule;
  _CurrentAgendaModule_28:import11.CurrentAgendaModule;
  _CityModule_29:import12.CityModule;
  _AppModule_30:import1.AppModule;
  __LOCALE_ID_31:any;
  __NgLocalization_32:import2.NgLocaleLocalization;
  __APP_ID_33:any;
  __IterableDiffers_34:any;
  __KeyValueDiffers_35:any;
  __DomSanitizer_36:import4.ɵe;
  __Sanitizer_37:any;
  __HAMMER_GESTURE_CONFIG_38:import4.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_39:any[];
  __EventManager_40:import4.EventManager;
  __ɵDomSharedStylesHost_41:import4.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_42:import4.ɵDomRendererFactory2;
  __RendererFactory2_43:any;
  __ɵSharedStylesHost_44:any;
  __Testability_45:import0.Testability;
  __Meta_46:import4.Meta;
  __Title_47:import4.Title;
  __BrowserXhr_48:import5.BrowserXhr;
  __ResponseOptions_49:import5.BaseResponseOptions;
  __XSRFStrategy_50:any;
  __XHRBackend_51:import5.XHRBackend;
  __RequestOptions_52:import5.BaseRequestOptions;
  __Http_53:any;
  __ɵi_54:import6.ɵi;
  __PositioningService_55:import13.PositioningService;
  __ComponentLoaderFactory_56:import14.ComponentLoaderFactory;
  __AgendaService_57:import15.AgendaService;
  __CityService_58:import16.CityService;
  __ActivatedRoute_59:any;
  __NoPreloading_60:import3.NoPreloading;
  __PreloadingStrategy_61:any;
  __RouterPreloader_62:import3.RouterPreloader;
  __PreloadAllModules_63:import3.PreloadAllModules;
  __ROUTER_INITIALIZER_64:any;
  __APP_BOOTSTRAP_LISTENER_65:any[];
  __AgendaResolver_66:import17.AgendaResolver;
  __CityResolver_67:import18.CityResolver;
  constructor(parent:import0.Injector) {
    super(parent,[
      import19.ModalBackdropComponentNgFactory,
      import20.AgendaListComponentNgFactory,
      import21.AgendaDetailsComponentNgFactory,
      import22.CityListComponentNgFactory,
      import23.CityDetailsComponentNgFactory,
      import24.AppComponentNgFactory
    ]
    ,[import24.AppComponentNgFactory]);
  }
  get _LOCALE_ID_31():any {
    if ((this.__LOCALE_ID_31 == null)) { (this.__LOCALE_ID_31 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_31;
  }
  get _NgLocalization_32():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_32 == null)) { (this.__NgLocalization_32 = new import2.NgLocaleLocalization(this._LOCALE_ID_31)); }
    return this.__NgLocalization_32;
  }
  get _APP_ID_33():any {
    if ((this.__APP_ID_33 == null)) { (this.__APP_ID_33 = import0.ɵg()); }
    return this.__APP_ID_33;
  }
  get _IterableDiffers_34():any {
    if ((this.__IterableDiffers_34 == null)) { (this.__IterableDiffers_34 = import0.ɵl()); }
    return this.__IterableDiffers_34;
  }
  get _KeyValueDiffers_35():any {
    if ((this.__KeyValueDiffers_35 == null)) { (this.__KeyValueDiffers_35 = import0.ɵm()); }
    return this.__KeyValueDiffers_35;
  }
  get _DomSanitizer_36():import4.ɵe {
    if ((this.__DomSanitizer_36 == null)) { (this.__DomSanitizer_36 = new import4.ɵe(this.parent.get(import4.DOCUMENT))); }
    return this.__DomSanitizer_36;
  }
  get _Sanitizer_37():any {
    if ((this.__Sanitizer_37 == null)) { (this.__Sanitizer_37 = this._DomSanitizer_36); }
    return this.__Sanitizer_37;
  }
  get _HAMMER_GESTURE_CONFIG_38():import4.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_38 == null)) { (this.__HAMMER_GESTURE_CONFIG_38 = new import4.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_38;
  }
  get _EVENT_MANAGER_PLUGINS_39():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_39 == null)) { (this.__EVENT_MANAGER_PLUGINS_39 = [
      new import4.ɵDomEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵKeyEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵHammerGesturesPlugin(this.parent.get(import4.DOCUMENT),this._HAMMER_GESTURE_CONFIG_38)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_39;
  }
  get _EventManager_40():import4.EventManager {
    if ((this.__EventManager_40 == null)) { (this.__EventManager_40 = new import4.EventManager(this._EVENT_MANAGER_PLUGINS_39,this.parent.get(import0.NgZone))); }
    return this.__EventManager_40;
  }
  get _ɵDomSharedStylesHost_41():import4.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_41 == null)) { (this.__ɵDomSharedStylesHost_41 = new import4.ɵDomSharedStylesHost(this.parent.get(import4.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_41;
  }
  get _ɵDomRendererFactory2_42():import4.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_42 == null)) { (this.__ɵDomRendererFactory2_42 = new import4.ɵDomRendererFactory2(this._EventManager_40,this._ɵDomSharedStylesHost_41)); }
    return this.__ɵDomRendererFactory2_42;
  }
  get _RendererFactory2_43():any {
    if ((this.__RendererFactory2_43 == null)) { (this.__RendererFactory2_43 = this._ɵDomRendererFactory2_42); }
    return this.__RendererFactory2_43;
  }
  get _ɵSharedStylesHost_44():any {
    if ((this.__ɵSharedStylesHost_44 == null)) { (this.__ɵSharedStylesHost_44 = this._ɵDomSharedStylesHost_41); }
    return this.__ɵSharedStylesHost_44;
  }
  get _Testability_45():import0.Testability {
    if ((this.__Testability_45 == null)) { (this.__Testability_45 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_45;
  }
  get _Meta_46():import4.Meta {
    if ((this.__Meta_46 == null)) { (this.__Meta_46 = new import4.Meta(this.parent.get(import4.DOCUMENT))); }
    return this.__Meta_46;
  }
  get _Title_47():import4.Title {
    if ((this.__Title_47 == null)) { (this.__Title_47 = new import4.Title(this.parent.get(import4.DOCUMENT))); }
    return this.__Title_47;
  }
  get _BrowserXhr_48():import5.BrowserXhr {
    if ((this.__BrowserXhr_48 == null)) { (this.__BrowserXhr_48 = new import5.BrowserXhr()); }
    return this.__BrowserXhr_48;
  }
  get _ResponseOptions_49():import5.BaseResponseOptions {
    if ((this.__ResponseOptions_49 == null)) { (this.__ResponseOptions_49 = new import5.BaseResponseOptions()); }
    return this.__ResponseOptions_49;
  }
  get _XSRFStrategy_50():any {
    if ((this.__XSRFStrategy_50 == null)) { (this.__XSRFStrategy_50 = import5.ɵb()); }
    return this.__XSRFStrategy_50;
  }
  get _XHRBackend_51():import5.XHRBackend {
    if ((this.__XHRBackend_51 == null)) { (this.__XHRBackend_51 = new import5.XHRBackend(this._BrowserXhr_48,this._ResponseOptions_49,this._XSRFStrategy_50)); }
    return this.__XHRBackend_51;
  }
  get _RequestOptions_52():import5.BaseRequestOptions {
    if ((this.__RequestOptions_52 == null)) { (this.__RequestOptions_52 = new import5.BaseRequestOptions()); }
    return this.__RequestOptions_52;
  }
  get _Http_53():any {
    if ((this.__Http_53 == null)) { (this.__Http_53 = import5.ɵc(this._XHRBackend_51,this._RequestOptions_52)); }
    return this.__Http_53;
  }
  get _ɵi_54():import6.ɵi {
    if ((this.__ɵi_54 == null)) { (this.__ɵi_54 = new import6.ɵi()); }
    return this.__ɵi_54;
  }
  get _PositioningService_55():import13.PositioningService {
    if ((this.__PositioningService_55 == null)) { (this.__PositioningService_55 = new import13.PositioningService()); }
    return this.__PositioningService_55;
  }
  get _ComponentLoaderFactory_56():import14.ComponentLoaderFactory {
    if ((this.__ComponentLoaderFactory_56 == null)) { (this.__ComponentLoaderFactory_56 = new import14.ComponentLoaderFactory(this.componentFactoryResolver,this.parent.get(import0.NgZone),this,this._PositioningService_55)); }
    return this.__ComponentLoaderFactory_56;
  }
  get _AgendaService_57():import15.AgendaService {
    if ((this.__AgendaService_57 == null)) { (this.__AgendaService_57 = new import15.AgendaService(this._Http_53)); }
    return this.__AgendaService_57;
  }
  get _CityService_58():import16.CityService {
    if ((this.__CityService_58 == null)) { (this.__CityService_58 = new import16.CityService(this._Http_53)); }
    return this.__CityService_58;
  }
  get _ActivatedRoute_59():any {
    if ((this.__ActivatedRoute_59 == null)) { (this.__ActivatedRoute_59 = import3.ɵf(this._Router_24)); }
    return this.__ActivatedRoute_59;
  }
  get _NoPreloading_60():import3.NoPreloading {
    if ((this.__NoPreloading_60 == null)) { (this.__NoPreloading_60 = new import3.NoPreloading()); }
    return this.__NoPreloading_60;
  }
  get _PreloadingStrategy_61():any {
    if ((this.__PreloadingStrategy_61 == null)) { (this.__PreloadingStrategy_61 = this._NoPreloading_60); }
    return this.__PreloadingStrategy_61;
  }
  get _RouterPreloader_62():import3.RouterPreloader {
    if ((this.__RouterPreloader_62 == null)) { (this.__RouterPreloader_62 = new import3.RouterPreloader(this._Router_24,this._NgModuleFactoryLoader_22,this._Compiler_21,this,this._PreloadingStrategy_61)); }
    return this.__RouterPreloader_62;
  }
  get _PreloadAllModules_63():import3.PreloadAllModules {
    if ((this.__PreloadAllModules_63 == null)) { (this.__PreloadAllModules_63 = new import3.PreloadAllModules()); }
    return this.__PreloadAllModules_63;
  }
  get _ROUTER_INITIALIZER_64():any {
    if ((this.__ROUTER_INITIALIZER_64 == null)) { (this.__ROUTER_INITIALIZER_64 = import3.ɵi(this._ɵg_3)); }
    return this.__ROUTER_INITIALIZER_64;
  }
  get _APP_BOOTSTRAP_LISTENER_65():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_65 == null)) { (this.__APP_BOOTSTRAP_LISTENER_65 = [this._ROUTER_INITIALIZER_64]); }
    return this.__APP_BOOTSTRAP_LISTENER_65;
  }
  get _AgendaResolver_66():import17.AgendaResolver {
    if ((this.__AgendaResolver_66 == null)) { (this.__AgendaResolver_66 = new import17.AgendaResolver(this._AgendaService_57,this._Router_24,this._Http_53)); }
    return this.__AgendaResolver_66;
  }
  get _CityResolver_67():import18.CityResolver {
    if ((this.__CityResolver_67 == null)) { (this.__CityResolver_67 = new import18.CityResolver(this._CityService_58,this._Router_24,this._Http_53)); }
    return this.__CityResolver_67;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ErrorHandler_1 = import4.ɵa();
    this._NgProbeToken_2 = [import3.ɵb()];
    this._ɵg_3 = new import3.ɵg(this);
    this._APP_INITIALIZER_4 = [
      import0.ɵo,
      import4.ɵc(this.parent.get(import4.NgProbeToken,(null as any)),this._NgProbeToken_2),
      import3.ɵh(this._ɵg_3)
    ]
    ;
    this._ApplicationInitStatus_5 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_4);
    this._ɵf_6 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_5);
    this._ApplicationRef_7 = this._ɵf_6;
    this._ApplicationModule_8 = new import0.ApplicationModule(this._ApplicationRef_7);
    this._BrowserModule_9 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._HttpModule_10 = new import5.HttpModule();
    this._ɵba_11 = new import6.ɵba();
    this._FormsModule_12 = new import6.FormsModule();
    this._ModalModule_13 = new import7.ModalModule();
    this._Angular2FontawesomeModule_14 = new import8.Angular2FontawesomeModule();
    this._ɵa_15 = import3.ɵd(this.parent.get(import3.Router,(null as any)));
    this._UrlSerializer_16 = new import3.DefaultUrlSerializer();
    this._RouterOutletMap_17 = new import3.RouterOutletMap();
    this._ROUTER_CONFIGURATION_18 = {};
    this._LocationStrategy_19 = import3.ɵc(this.parent.get(import2.PlatformLocation),this.parent.get(import2.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_18);
    this._Location_20 = new import2.Location(this._LocationStrategy_19);
    this._Compiler_21 = new import0.Compiler();
    this._NgModuleFactoryLoader_22 = new import0.SystemJsNgModuleLoader(this._Compiler_21,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
    this._ROUTES_23 = [
      [
        {
          path: 'agenda',
          component: import25.AgendaListComponent
        }
        ,
        {
          path: 'agenda/:id',
          component: import26.AgendaDetailsComponent,
          resolve: {agenda: import17.AgendaResolver}
        }

      ]
      ,
      [
        {
          path: 'city',
          component: import27.CityListComponent
        }
        ,
        {
          path: 'city/:id',
          component: import28.CityDetailsComponent,
          resolve: {city: import18.CityResolver}
        }

      ]
      ,
      [
        {
          path: '',
          redirectTo: 'city',
          pathMatch: 'full'
        }
        ,
        {
          path: '',
          redirectTo: 'agenda',
          pathMatch: 'full'
        }

      ]

    ]
    ;
    this._Router_24 = import3.ɵe(this._ApplicationRef_7,this._UrlSerializer_16,this._RouterOutletMap_17,this._Location_20,this,this._NgModuleFactoryLoader_22,this._Compiler_21,this._ROUTES_23,this._ROUTER_CONFIGURATION_18,this.parent.get(import3.UrlHandlingStrategy,(null as any)),this.parent.get(import3.RouteReuseStrategy,(null as any)));
    this._RouterModule_25 = new import3.RouterModule(this._ɵa_15,this._Router_24);
    this._SharedModule_26 = new import9.SharedModule();
    this._AgendaModule_27 = new import10.AgendaModule();
    this._CurrentAgendaModule_28 = new import11.CurrentAgendaModule();
    this._CityModule_29 = new import12.CityModule();
    this._AppModule_30 = new import1.AppModule();
    return this._AppModule_30;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_2; }
    if ((token === import3.ɵg)) { return this._ɵg_3; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_4; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_5; }
    if ((token === import0.ɵf)) { return this._ɵf_6; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_7; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_8; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_9; }
    if ((token === import5.HttpModule)) { return this._HttpModule_10; }
    if ((token === import6.ɵba)) { return this._ɵba_11; }
    if ((token === import6.FormsModule)) { return this._FormsModule_12; }
    if ((token === import7.ModalModule)) { return this._ModalModule_13; }
    if ((token === import8.Angular2FontawesomeModule)) { return this._Angular2FontawesomeModule_14; }
    if ((token === import3.ɵa)) { return this._ɵa_15; }
    if ((token === import3.UrlSerializer)) { return this._UrlSerializer_16; }
    if ((token === import3.RouterOutletMap)) { return this._RouterOutletMap_17; }
    if ((token === import3.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_18; }
    if ((token === import2.LocationStrategy)) { return this._LocationStrategy_19; }
    if ((token === import2.Location)) { return this._Location_20; }
    if ((token === import0.Compiler)) { return this._Compiler_21; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_22; }
    if ((token === import3.ROUTES)) { return this._ROUTES_23; }
    if ((token === import3.Router)) { return this._Router_24; }
    if ((token === import3.RouterModule)) { return this._RouterModule_25; }
    if ((token === import9.SharedModule)) { return this._SharedModule_26; }
    if ((token === import10.AgendaModule)) { return this._AgendaModule_27; }
    if ((token === import11.CurrentAgendaModule)) { return this._CurrentAgendaModule_28; }
    if ((token === import12.CityModule)) { return this._CityModule_29; }
    if ((token === import1.AppModule)) { return this._AppModule_30; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_31; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_32; }
    if ((token === import0.APP_ID)) { return this._APP_ID_33; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_34; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_35; }
    if ((token === import4.DomSanitizer)) { return this._DomSanitizer_36; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_37; }
    if ((token === import4.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_38; }
    if ((token === import4.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_39; }
    if ((token === import4.EventManager)) { return this._EventManager_40; }
    if ((token === import4.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_41; }
    if ((token === import4.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_42; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_43; }
    if ((token === import4.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_44; }
    if ((token === import0.Testability)) { return this._Testability_45; }
    if ((token === import4.Meta)) { return this._Meta_46; }
    if ((token === import4.Title)) { return this._Title_47; }
    if ((token === import5.BrowserXhr)) { return this._BrowserXhr_48; }
    if ((token === import5.ResponseOptions)) { return this._ResponseOptions_49; }
    if ((token === import5.XSRFStrategy)) { return this._XSRFStrategy_50; }
    if ((token === import5.XHRBackend)) { return this._XHRBackend_51; }
    if ((token === import5.RequestOptions)) { return this._RequestOptions_52; }
    if ((token === import5.Http)) { return this._Http_53; }
    if ((token === import6.ɵi)) { return this._ɵi_54; }
    if ((token === import13.PositioningService)) { return this._PositioningService_55; }
    if ((token === import14.ComponentLoaderFactory)) { return this._ComponentLoaderFactory_56; }
    if ((token === import15.AgendaService)) { return this._AgendaService_57; }
    if ((token === import16.CityService)) { return this._CityService_58; }
    if ((token === import3.ActivatedRoute)) { return this._ActivatedRoute_59; }
    if ((token === import3.NoPreloading)) { return this._NoPreloading_60; }
    if ((token === import3.PreloadingStrategy)) { return this._PreloadingStrategy_61; }
    if ((token === import3.RouterPreloader)) { return this._RouterPreloader_62; }
    if ((token === import3.PreloadAllModules)) { return this._PreloadAllModules_63; }
    if ((token === import3.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_64; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_65; }
    if ((token === import17.AgendaResolver)) { return this._AgendaResolver_66; }
    if ((token === import18.CityResolver)) { return this._CityResolver_67; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_6.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_41 && this._ɵDomSharedStylesHost_41.ngOnDestroy());
    (this.__RouterPreloader_62 && this._RouterPreloader_62.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvc3VlX2MwMC9jb2RlL2phcGFubmluZy9qYXBhbm5pbmcvc3JjL2FwcC9hcHAubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2pvc3VlX2MwMC9jb2RlL2phcGFubmluZy9qYXBhbm5pbmcvc3JjL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
