/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './agenda.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
import * as import4 from 'ng2-bootstrap/modal/modal.module';
import * as import5 from '../shared/shared.module';
import * as import6 from '@angular/router';
import * as import7 from 'ng2-bootstrap/positioning/positioning.service';
import * as import8 from 'ng2-bootstrap/component-loader/component-loader.factory';
import * as import9 from './agenda.service';
import * as import10 from '../../node_modules/ng2-bootstrap/modal/modal-backdrop.component.ngfactory';
import * as import11 from './agenda-list.component.ngfactory';
import * as import12 from './agenda-details.component.ngfactory';
import * as import13 from '@angular/http';
import * as import14 from './agenda-list.component';
import * as import15 from './agenda-details.component';
import * as import16 from './agenda.resolver';
class AgendaModuleInjector extends import0.ɵNgModuleInjector<import1.AgendaModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _FormsModule_2:import3.FormsModule;
  _ModalModule_3:import4.ModalModule;
  _SharedModule_4:import5.SharedModule;
  _RouterModule_5:import6.RouterModule;
  _AgendaModule_6:import1.AgendaModule;
  __NgLocalization_7:import2.NgLocaleLocalization;
  __ɵi_8:import3.ɵi;
  __PositioningService_9:import7.PositioningService;
  __ComponentLoaderFactory_10:import8.ComponentLoaderFactory;
  _ROUTES_11:any[];
  __AgendaService_12:import9.AgendaService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import10.ModalBackdropComponentNgFactory,
      import11.AgendaListComponentNgFactory,
      import12.AgendaDetailsComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_7():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_7 == null)) { (this.__NgLocalization_7 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_7;
  }
  get _ɵi_8():import3.ɵi {
    if ((this.__ɵi_8 == null)) { (this.__ɵi_8 = new import3.ɵi()); }
    return this.__ɵi_8;
  }
  get _PositioningService_9():import7.PositioningService {
    if ((this.__PositioningService_9 == null)) { (this.__PositioningService_9 = new import7.PositioningService()); }
    return this.__PositioningService_9;
  }
  get _ComponentLoaderFactory_10():import8.ComponentLoaderFactory {
    if ((this.__ComponentLoaderFactory_10 == null)) { (this.__ComponentLoaderFactory_10 = new import8.ComponentLoaderFactory(this.componentFactoryResolver,this.parent.get(import0.NgZone),this,this._PositioningService_9)); }
    return this.__ComponentLoaderFactory_10;
  }
  get _AgendaService_12():import9.AgendaService {
    if ((this.__AgendaService_12 == null)) { (this.__AgendaService_12 = new import9.AgendaService(this.parent.get(import13.Http))); }
    return this.__AgendaService_12;
  }
  createInternal():import1.AgendaModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._FormsModule_2 = new import3.FormsModule();
    this._ModalModule_3 = new import4.ModalModule();
    this._SharedModule_4 = new import5.SharedModule();
    this._RouterModule_5 = new import6.RouterModule(this.parent.get(import6.ɵa,(null as any)),this.parent.get(import6.Router,(null as any)));
    this._AgendaModule_6 = new import1.AgendaModule();
      this._ROUTES_11 = [[
        {
          path: 'agenda',
          component: import14.AgendaListComponent
        }
        ,
        {
          path: 'agenda/:id',
          component: import15.AgendaDetailsComponent,
          resolve: {agenda: import16.AgendaResolver}
        }

      ]
    ];
    return this._AgendaModule_6;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.FormsModule)) { return this._FormsModule_2; }
    if ((token === import4.ModalModule)) { return this._ModalModule_3; }
    if ((token === import5.SharedModule)) { return this._SharedModule_4; }
    if ((token === import6.RouterModule)) { return this._RouterModule_5; }
    if ((token === import1.AgendaModule)) { return this._AgendaModule_6; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_7; }
    if ((token === import3.ɵi)) { return this._ɵi_8; }
    if ((token === import7.PositioningService)) { return this._PositioningService_9; }
    if ((token === import8.ComponentLoaderFactory)) { return this._ComponentLoaderFactory_10; }
    if ((token === import6.ROUTES)) { return this._ROUTES_11; }
    if ((token === import9.AgendaService)) { return this._AgendaService_12; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AgendaModuleNgFactory:import0.NgModuleFactory<import1.AgendaModule> = new import0.NgModuleFactory<any>(AgendaModuleInjector,import1.AgendaModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvc3VlX2MwMC9jb2RlL2phcGFubmluZy9qYXBhbm5pbmcvc3JjL2FwcC9hZ2VuZGEvYWdlbmRhLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9qb3N1ZV9jMDAvY29kZS9qYXBhbm5pbmcvamFwYW5uaW5nL3NyYy9hcHAvYWdlbmRhL2FnZW5kYS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
