/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['h3[_ngcontent-%COMP%] {\n	margin-left: 20.6em;\n	color: mediumvioletred;\n}\n\np[_ngcontent-%COMP%] {\n	margin-bottom: 0;\n	padding-left: .5em;\n}\n\nh4[_ngcontent-%COMP%] {\n	color: royalblue;\n}\n\n.deletion[_ngcontent-%COMP%] {\n	margin-left: 30em;\n}\n\n.media-body[_ngcontent-%COMP%] {\n	vertical-align: middle;\n	border: 1px solid #1bb9b9;\n	padding: 7px;\n}\n\nimg.media-object[_ngcontent-%COMP%] {\n	margin-top: 1.6em;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvc3VlX2MwMC9jb2RlL2phcGFubmluZy9qYXBhbm5pbmcvc3JjL2FwcC9hZ2VuZGEvYWdlbmRhLWRldGFpbHMuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9qb3N1ZV9jMDAvY29kZS9qYXBhbm5pbmcvamFwYW5uaW5nL3NyYy9hcHAvYWdlbmRhL2FnZW5kYS1kZXRhaWxzLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
